
# @import ./proto.http
proto < {{webitel_proto}}/im/service/auth/v1/service_account.proto
includeDirs: [`${webitel_proto}/im`,`/usr/local/include`]
keepCase: true
longs: String
enums: String
defaults: false
oneofs: true

@client_id=
@api_token=

###

# @name inspect
GRPC /webitel.im.service.auth.v1.Account/Inspect
x-webitel-device: {{device_id}}
x-webitel-client: {{client_id}}
x-webitel-access: {{api_token}}

{

}

###

# @debug
# @name login
GRPC /webitel.im.service.auth.v1.Account/Token
x-webitel-device: {{device_id}}
x-webitel-access: {{api_token}}

{
  "state": "my_app_client_login_state_id",
  "scope": [
    "send_messages",
    "edit_messages"
  ],
  "client_id": "{{client_id}}",
  "identity": {
    "iss": "https://example.com/people",
    "sub": "j.doe",
    "name": "John Doe",
    "givenName": "John",
    "middleName": "Edward",
    "familyName": "Doe",
    "birthdate": "",
    "zoneinfo": "",
    "profile": "",
    "picture": "",
    "gender": "male",
    "locale": "uk-UA",
    "email": "j.doe@example.com",
    "emailVerified": false,
    "phoneNumber": "",
    "phoneNumberVerified": false
  }
}

// Script section starts after a blank line
{{@response
  // Check if the request was successful (no gRPC error)
  // The gRPC spec says a successful call returns an OK status (HTTP 200)
  // httpYac handles the status internally, if the script runs the call was likely successful
  
  if (response.parsedBody && response.parsedBody.token) {
    // If the 'token' field exists in the response, save it as an environment variable
    console.log("Login successful, extracting access_token.");
    
    // Access the 'token' field
    exports.api_token = response.parsedBody.token.access_token;
    
    // // Store it in the httpYac environment variables for reuse
    // httpyac.variables.set("authToken", authToken);
  } else {
    console.error("Login failed or 'token' field missing from response.");
    // You could also check response status details if needed, but in case of success 
    // the parsedBody contains the expected message
  }
}}

# {{@response
#   exports.api_token = JSON.parse(response.body).token.access_token;
# }}

###

# @name devices
GRPC /webitel.im.service.auth.v1.Account/GetAuthorizations
x-webitel-device: {{device_id}}
x-webitel-access: {{api_token}}
{
  "size": -1
}

###

# @name register_device
GRPC /webitel.im.service.auth.v1.Account/RegisterDevice
x-webitel-device: {{device_id}}
x-webitel-client: {{client_id}}
x-webitel-access: {{api_token}}

{
  "push": {
    "fcm": "my_device_fcms_registration_token_fake"
  }
}

###

# @name unregister_device
GRPC /webitel.im.service.auth.v1.Account/UnregisterDevice
x-webitel-device: {{device_id}}
x-webitel-client: {{client_id}}
x-webitel-access: {{api_token}}

{
  "push": {
    "fcm": "my_device_fcms_registration_token_fake"
  }
}

###

# @name logout
GRPC /webitel.im.service.auth.v1.Account/Logout
x-webitel-device: {{device_id}}
x-webitel-access: {{api_token}}

{
  
}